name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Fat Jar
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: shadowJar
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Build GraalVM Native Image
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: nativeImage
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/graal/klisp
            build/libs/klisp.jar
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}